version: "2"
services:
  app:
    image: kevineye/airplay-to-bluetooth
    build: .
    devices:
      - /dev/bus/usb # or set a specific device
    volumes:
      - ./app:/app
      - ./devices:/var/lib/bluetooth
      - ./test:/tmp/test
      - ./config:/root/.config
      - ./pulse:/root/.pulse
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      BT_DEVICE: B8:AD:3E:27:D0:8A

  shell:
    extends:
      service: app
    volumes:
      - ./app:/app
      - ./test:/tmp/test
    stdin_open: true
    tty: true
    command: 'sh'
    working_dir: /app
